from rest_framework import serializers


class CharacterSerializer(serializers.Serializer):
    list_href = serializers.URLField(source="characters-href")
    image = serializers.URLField(source="Image-src")
    name = serializers.CharField(max_length=100)
    nationality = serializers.CharField(max_length=100, allow_blank=True,source="Nationality")
    ethnicity = serializers.CharField(max_length=100,source="Ethnicity")
    age = serializers.CharField(max_length=50, allow_blank=True,source="Age")
    gender = serializers.CharField(max_length=50,source="Gender")
    born = serializers.CharField(max_length=100, allow_blank=True,source="Born")
    died = serializers.CharField(max_length=100, allow_blank=True,source="Died")
    eye_color = serializers.CharField(max_length=50, allow_blank=True,source="Eye color")
    hair_color = serializers.CharField(max_length=50, allow_blank=True,source="Hair color")
    skin_color = serializers.CharField(max_length=50, allow_blank=True,source="Skin color")
    love_interest = serializers.CharField(max_length=100, allow_blank=True,source="Love interest")
    allies = serializers.CharField(max_length=200,source="Allies")
    enemies = serializers.CharField(max_length=200, allow_blank=True,source="Enemies")
    weapon_of_choice = serializers.CharField(max_length=100,source="Weapon of choice")
    fighting_styles = serializers.CharField(max_length=200,source="Fighting styles")
    profession = serializers.CharField(max_length=100,source="Profession")
    position = serializers.CharField(max_length=200,source="Position")
    predecessor = serializers.CharField(max_length=100, allow_blank=True,source="Predecessor")
    successor = serializers.CharField(max_length=100, allow_blank=True,source="Successor")
    affiliation = serializers.CharField(max_length=200,source="Affiliation")
    first_appearance = serializers.CharField(max_length=200,source="First appearance")
    last_appearance = serializers.CharField(max_length=200, allow_blank=True,source="Last appearance")
    voiced_by = serializers.CharField(max_length=200, allow_blank=True,source="Voiced by")
